### ISSUE TITLE
Windows build fail: error LNK2001

### ISSUE THREAD

**Issue by pbertoni89** [config4star/config4cpp#3]
Environment: Windows 10 x64, Visual Studio 12.0.
Instead of `vcvars32.bat` I ran `"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"` (the former doesn't exist)

Then `nmake.exe -f Makefile.win` outputs (snippets)

> Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
>  cd src
>  nmake -f Makefile.win all
> .....................................................................................................
> CL /c /I..\include /DWIN32 /GX /Zi /nologo /GZ /DDEBUG SchemaTypeTypedef.cpp
> cl : Command line warning D9035 : option 'GX' has been deprecated and will be removed in a future release
> cl : Command line warning D9036 : use 'EHsc' instead of 'GX'
> cl : Command line warning D9035 : option 'GZ' has been deprecated and will be removed in a future release
> cl : Command line warning D9036 : use 'RTC1' instead of 'GZ'
> SchemaTypeTypedef.cpp
>         LIB /out:config4cpp.lib SchemaLex.obj  SchemaParser.obj  MBChar.obj  SchemaValidator.obj  platform.obj  util.obj  Configuration.obj  DefaultSecurity.obj  DefaultSecurityConfiguration.obj  ConfigurationException.obj  ConfigurationImpl.obj  ConfigParser.obj  UidIdentifierProcessor.obj  ConfigScope.obj  ConfigScopeEntry.obj  ConfigItem.obj  LexToken.obj  LexBase.obj  ConfigLex.obj  StringBuffer.obj  StringVector.obj  SchemaType.obj  SchemaTypeBoolean.obj  SchemaTypeDurationMilliseconds.obj  SchemaTypeDurationSeconds.obj  SchemaTypeEnum.obj  SchemaTypeFloat.obj  SchemaTypeFloatWithUnits.obj  SchemaTypeInt.obj  SchemaTypeIntWithUnits.obj  SchemaTypeMemorySizeBytes.obj  SchemaTypeMemorySizeKB.obj  SchemaTypeMemorySizeMB.obj  SchemaTypeScope.obj  SchemaTypeString.obj  SchemaTypeUnitsWithFloat.obj  SchemaTypeUnitsWithInt.obj  SchemaTypeList.obj  SchemaTypeTable.obj  SchemaTypeTuple.obj  SchemaTypeTypedef.obj

Seems compiled. Now Linker starts and fails

> Microsoft (R) Library Manager Version 12.00.40629.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
>  copy config4cpp.lib ..\lib
>  1 file(s) copied.
>  LINK /out:config4cpp.exe config4cpp.obj config4cpp.lib
> config4cpp.lib(SchemaValidator.obj) : **error LNK2001: unresolved external symbol "protected: virtual void __thiscall config4cpp::SchemaTypeDurationMicroseconds::checkRule(class config4cpp::SchemaValidator const *,class config4cpp::Configuration const *,char const *,class config4cpp::StringVector const &,char const *)const " (?checkRule@SchemaTypeDurationMicroseconds@config4cpp@@MBEXPBVSchemaValidator@2@PBVConfiguration@2@PBDABVStringVector@2@2@Z)**
> config4cpp.lib(SchemaValidator.obj) : **error LNK2001: unresolved external symbol "protected: virtual bool __thiscall config4cpp::SchemaTypeDurationMicroseconds::isA(class config4cpp::SchemaValidator const *,class config4cpp::Configuration const *,char const *,char const *,class config4cpp::StringVector const &,int,class config4cpp::StringBuffer &)const " (?isA@SchemaTypeDurationMicroseconds@config4cpp@@MBE_NPBVSchemaValidator@2@PBVConfiguration@2@PBD2ABVStringVector@2@HAAVStringBuffer@2@@Z)**
> config4cpp.exe : fatal error LNK1120: 2 unresolved externals
> NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\LINK.EXE"' : return code '0x460'
> Stop.
> NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.EXE"' : return code '0x2'
> Stop.

**Comment by justinbrock** [comment]
I figured out the problem with this one. The makefile in the src directory is incorrect. It doesn't link the microseconds one. Not sure if you still need an answer for this or not. This project seems to have been discontinued...?

**Comment by tincumagic** [comment]
My tips for building this excelent library and integrating it with Visual Studio 2019.

1. Extract in your visual studio project folder the content of:
http://www.config4star.org/download/config4cpp.zip

2. Automatically call nmake with vcvars32.bat environment for project building when you build your project before the linking stage.

Go to Project Property 
look under Configuration Properties -> Build Events -> Pre-Link Events and add:
cd config4cpp
nmake -f Makefile.win


3, Specify the include path where Visual Studio shall look:
look under Configuration Properties -> C/C++ -> General -> Additional Include Directories and add folder:
c:\project\config4cpp\include;


4. Specify the lib path where Visual Studio shall look:
look under Configuration Properties -> Linker -> General -> Additional Library Directories and add folder:
c:\project\config4cpp\lib

**Comment by tincumagic** [comment]
This project looks dead but: the library quality, the rich features and the documentation is of exceptional quality.

This is the rare treasure unfortunately forgotten on the floor of the ocean that I found when searching for a config parse and I have looked over many libraries.
